package report

import (
	"fmt"
	"strings"

	"pdfnest-backend/internal/analyzer/engine"
	"pdfnest-backend/internal/analyzer/engine/graph"
	"pdfnest-backend/internal/analyzer/engine/intelligence"
)

// GenerateMarkdownReport transforms a CanonicalAnalysisResult into a comprehensive 19-section Architecture Analysis Report.
func GenerateMarkdownReport(res *engine.CanonicalAnalysisResult) string {
	if res == nil {
		return "# Architecture Analysis Report\n\nNo analysis result available.\n"
	}

	var sb strings.Builder

	repoName := res.Repository.Name
	if repoName == "" {
		repoName = "Repository"
	}

	sb.WriteString(fmt.Sprintf("# Architecture Analysis Report: %s\n\n", repoName))
	sb.WriteString(fmt.Sprintf("> Generated by PDFNest Repository Analyzer (Engine: `%s` v%s)\n\n", res.Provenance.Engine, res.Provenance.EngineVersion))

	// Section 1: Executive Summary
	sb.WriteString("## 1. Executive Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Repository Name:** `%s`\n", repoName))
	sb.WriteString(fmt.Sprintf("- **Analysis Timestamp:** `%s`\n", res.CreatedAt.UTC().Format("2006-01-02 15:04:05 UTC")))
	sb.WriteString(fmt.Sprintf("- **Complexity Tier:** `%s` (Score: %.1f)\n", res.Provenance.ComplexityTier, res.Provenance.ComplexityScore))
	sb.WriteString(fmt.Sprintf("- **Analysis Duration:** %d ms\n", res.Provenance.DurationMs))

	if res.Intelligence != nil && res.Intelligence.Scorecard != nil {
		sc := res.Intelligence.Scorecard
		sb.WriteString(fmt.Sprintf("- **Overall Architecture Grade:** `Grade %s` (Score: %.1f/100)\n", sc.OverallGrade, sc.OverallScore))
	}

	if len(res.Metrics.Languages) > 0 {
		var langParts []string
		for _, l := range res.Metrics.Languages {
			langParts = append(langParts, fmt.Sprintf("%s (%.1f%%)", l.Name, l.Percentage))
		}
		sb.WriteString(fmt.Sprintf("- **Primary Languages:** %s\n", strings.Join(langParts, ", ")))
	}
	sb.WriteString("\n")

	// Section 2: Repository Overview
	sb.WriteString("## 2. Repository Overview\n\n")
	sb.WriteString("| Metric | Value |\n|---|---|\n")
	sb.WriteString(fmt.Sprintf("| Total Discovered Files | %d |\n", res.Metrics.TotalFiles))
	sb.WriteString(fmt.Sprintf("| Included Files Analyzed | %d |\n", res.Metrics.IncludedFiles))
	sb.WriteString(fmt.Sprintf("| Excluded Files | %d |\n", res.Metrics.ExcludedFiles))
	sb.WriteString(fmt.Sprintf("| Total File Size | %.2f MB (%d bytes) |\n", float64(res.Metrics.TotalBytes)/(1024*1024), res.Metrics.TotalBytes))
	if res.Metrics.LinesOfCode > 0 {
		sb.WriteString(fmt.Sprintf("| Estimated Lines of Code | %d |\n", res.Metrics.LinesOfCode))
	}
	if res.Repository.DefaultBranch != nil {
		sb.WriteString(fmt.Sprintf("| Default Branch | `%s` |\n", *res.Repository.DefaultBranch))
	}
	if res.Repository.CommitHash != nil {
		sb.WriteString(fmt.Sprintf("| Commit Hash | `%s` |\n", *res.Repository.CommitHash))
	}
	sb.WriteString(fmt.Sprintf("| Runtime Dependencies | %d |\n", len(res.Dependencies.Runtime)))
	sb.WriteString(fmt.Sprintf("| Development Dependencies | %d |\n", len(res.Dependencies.Development)))
	sb.WriteString(fmt.Sprintf("| Static API Routes | %d |\n", len(res.Routes)))
	sb.WriteString("\n")

	// Section 3: Project Structure
	sb.WriteString("## 3. Project Structure\n\n")
	if res.Structure != nil {
		sb.WriteString(fmt.Sprintf("Structured inventory contains **%d** directories and **%d** files.\n\n", res.Structure.TotalDirs, res.Structure.TotalFiles))
	}
	if res.StructureTree != "" {
		sb.WriteString("```text\n")
		sb.WriteString(res.StructureTree)
		sb.WriteString("\n```\n\n")
	} else {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 4: Technology Stack
	sb.WriteString("## 4. Technology Stack\n\n")
	if len(res.Technologies) == 0 {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	} else {
		sb.WriteString("| Technology | Category | Confidence | Version | Negative Assertions Passed |\n|---|---|---|---|---|\n")
		for _, t := range res.Technologies {
			ver := "-"
			if t.Version != nil && *t.Version != "" {
				ver = fmt.Sprintf("`%s`", *t.Version)
			}
			neg := "-"
			if len(t.NegativeAssertionsPassed) > 0 {
				neg = strings.Join(t.NegativeAssertionsPassed, ", ")
			}
			sb.WriteString(fmt.Sprintf("| **%s** | %s | `%s` | %s | %s |\n", t.Name, t.Category, t.Confidence, ver, neg))
		}
		sb.WriteString("\n")
	}

	// Section 5: Architecture / System Topology
	sb.WriteString("## 5. Architecture / System Topology\n\n")
	hasArch := false
	if res.Intelligence != nil {
		if archList, ok := res.Intelligence.Architecture.([]intelligence.ArchitectureComponent); ok && len(archList) > 0 {
			hasArch = true
			sb.WriteString("| Tier | Entity ID | Epistemic Confidence | Evidence Count |\n|---|---|---|---|\n")
			for _, comp := range archList {
				sb.WriteString(fmt.Sprintf("| **%s** | `%s` | `%s` | %d |\n", comp.Tier, comp.EntityID, comp.Confidence, len(comp.Evidence)))
			}
			sb.WriteString("\n")
		}
	}
	if !hasArch {
		// Fallback to graph entities or technologies
		if res.Deployment.DockerAvailable || len(res.Routes) > 0 {
			sb.WriteString("- **API Layer:** Detected REST/HTTP endpoints and service controllers.\n")
			if res.Deployment.DockerAvailable {
				sb.WriteString("- **Containerization / Deployment:** Docker container deployment enabled.\n")
			}
			sb.WriteString("\n")
		} else {
			sb.WriteString("No findings were produced by this analyzer.\n\n")
		}
	}

	// Section 6: Entities
	sb.WriteString("## 6. Entities\n\n")
	hasEntities := false
	if res.Graph != nil {
		if sg, ok := res.Graph.(*graph.SerializedGraph); ok && len(sg.Entities) > 0 {
			hasEntities = true
			sb.WriteString(fmt.Sprintf("Total canonical entities extracted: **%d**\n\n", len(sg.Entities)))
			sb.WriteString("| Entity ID | Kind | Name | Relative Path |\n|---|---|---|---|\n")
			limit := 40
			if len(sg.Entities) < limit {
				limit = len(sg.Entities)
			}
			for i := 0; i < limit; i++ {
				e := sg.Entities[i]
				p := e.Path
				if p == "" {
					p = "-"
				}
				sb.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` | `%s` |\n", e.ID, e.Kind, e.Name, p))
			}
			if len(sg.Entities) > limit {
				sb.WriteString(fmt.Sprintf("\n*(Showing %d of %d canonical entities)*\n", limit, len(sg.Entities)))
			}
			sb.WriteString("\n")
		}
	}
	if !hasEntities {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 7: Relationship Graph
	sb.WriteString("## 7. Relationship Graph\n\n")
	if res.GraphMetrics != nil {
		if gm, ok := res.GraphMetrics.(*graph.GraphMetrics); ok {
			sb.WriteString("| Graph Metric | Value |\n|---|---|\n")
			sb.WriteString(fmt.Sprintf("| Total Nodes (Entities) | %d |\n", gm.EntityCount))
			sb.WriteString(fmt.Sprintf("| Total Edges (Relationships) | %d |\n", gm.EdgeCount))
			sb.WriteString(fmt.Sprintf("| Confirmed Edges | %d |\n", gm.ConfirmedEdgeCount))
			sb.WriteString(fmt.Sprintf("| Inferred Edges | %d |\n", gm.InferredEdgeCount))
			sb.WriteString(fmt.Sprintf("| Evidence Coverage | %.1f%% |\n", gm.EvidenceCoveragePct))
			sb.WriteString(fmt.Sprintf("| Dependency Cycles | %d |\n", gm.CycleCount))
			sb.WriteString(fmt.Sprintf("| Orphan Entities | %d |\n", gm.OrphanEntityCount))
			sb.WriteString(fmt.Sprintf("| Unresolved References | %d |\n", gm.UnresolvedReferences))
			sb.WriteString("\n")
		}
	} else {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 8: Execution Flows
	sb.WriteString("## 8. Execution Flows\n\n")
	hasFlows := false
	if res.Intelligence != nil {
		if flowList, ok := res.Intelligence.Flow.([]intelligence.ExecutionFlow); ok && len(flowList) > 0 {
			hasFlows = true
			for idx, flow := range flowList {
				sb.WriteString(fmt.Sprintf("### Flow %d: `%s`\n\n", idx+1, flow.ID))
				for _, step := range flow.Steps {
					sb.WriteString(fmt.Sprintf("- **%s**: `%s` → `%s` *(Confidence: `%s`)*\n", step.Action, step.EntityID, step.TargetID, step.Confidence))
				}
				sb.WriteString("\n")
			}
		}
	}
	if !hasFlows {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 9: API / Entry Points
	sb.WriteString("## 9. API / Entry Points\n\n")
	if len(res.Routes) == 0 {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	} else {
		sb.WriteString("| Method | Endpoint Path | Inferred Handler | Auth Required | Source File |\n|---|---|---|---|---|\n")
		for _, r := range res.Routes {
			h := "inline"
			if r.InferredHandler != nil && *r.InferredHandler != "" {
				h = *r.InferredHandler
			}
			auth := "No"
			if r.AuthRequired {
				auth = "Yes"
			}
			sf := r.SourceFile
			if r.LineNumber != nil && *r.LineNumber > 0 {
				sf = fmt.Sprintf("%s:%d", sf, *r.LineNumber)
			}
			sb.WriteString(fmt.Sprintf("| **%s** | `%s` | `%s` | %s | `%s` |\n", r.Method, r.Path, h, auth, sf))
		}
		sb.WriteString("\n")
	}

	// Section 10: Change Impact Analysis
	sb.WriteString("## 10. Change Impact Analysis\n\n")
	hasImpact := false
	if res.Intelligence != nil {
		if impactMap, ok := res.Intelligence.Impact.(map[string]*intelligence.ImpactAnalysis); ok && len(impactMap) > 0 {
			hasImpact = true
			sb.WriteString("| Target Entity | Blast Radius (Direct / Indirect) | Affected Routes | Affected Services | Risk Score |\n|---|---|---|---|---|\n")
			for entID, imp := range impactMap {
				sb.WriteString(fmt.Sprintf("| `%s` | %d direct / %d indirect | %d | %d | `%s` |\n",
					entID, imp.DirectDependents, imp.IndirectDependents, imp.AffectedRoutes, imp.AffectedServices, imp.RiskScore))
			}
			sb.WriteString("\n")
		}
	}
	if !hasImpact {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 11: Engineering Hotspots
	sb.WriteString("## 11. Engineering Hotspots\n\n")
	hasHotspots := false
	if res.Intelligence != nil {
		if hotspotList, ok := res.Intelligence.Hotspots.([]intelligence.HotspotScore); ok && len(hotspotList) > 0 {
			hasHotspots = true
			sb.WriteString("| Entity | Fan-In | Fan-Out | Centrality | Complexity | Tested | Hotspot Metric |\n|---|---|---|---|---|---|---|\n")
			for _, hs := range hotspotList {
				tested := "NO"
				if hs.IsTested {
					tested = "YES"
				}
				sb.WriteString(fmt.Sprintf("| `%s` | %d | %d | %.2f | %.1f | %s | **%.1f** |\n",
					hs.EntityID, hs.FanIn, hs.FanOut, hs.Centrality, hs.Complexity, tested, hs.HotspotMetric))
			}
			sb.WriteString("\n")
		}
	}
	if !hasHotspots {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 12: Security Findings
	sb.WriteString("## 12. Security Findings\n\n")
	hasSec := false
	if res.Intelligence != nil {
		if secList, ok := res.Intelligence.Security.([]intelligence.SecurityFinding); ok && len(secList) > 0 {
			hasSec = true
			for _, sec := range secList {
				sb.WriteString(fmt.Sprintf("### [%s] %s (`%s`)\n\n", sec.Severity, sec.Title, sec.RuleID))
				sb.WriteString(fmt.Sprintf("- **Location:** `%s`\n", sec.EntityID))
				sb.WriteString(fmt.Sprintf("- **Description:** %s\n", sec.Description))
				if sec.Remediation != "" {
					sb.WriteString(fmt.Sprintf("- **Remediation:** %s\n", sec.Remediation))
				}
				sb.WriteString(fmt.Sprintf("- **Confidence:** `%s`\n\n", sec.Confidence))
			}
		}
	}
	if !hasSec {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 13: Test Intelligence
	sb.WriteString("## 13. Test Intelligence\n\n")
	hasTestIntel := false
	if res.Intelligence != nil {
		if ti, ok := res.Intelligence.Test.(intelligence.TestIntelligence); ok {
			hasTestIntel = true
			if len(ti.UntestedComponents) > 0 {
				sb.WriteString("### High-FanIn Untested Components\n\n")
				sb.WriteString("| Component | Kind | Fan-In |\n|---|---|---|\n")
				for _, uc := range ti.UntestedComponents {
					sb.WriteString(fmt.Sprintf("| `%s` | `%s` | %d |\n", uc.Name, uc.Kind, uc.FanIn))
				}
				sb.WriteString("\n")
			}
			if len(ti.Mappings) > 0 {
				sb.WriteString("### Test Mappings\n\n")
				for _, tm := range ti.Mappings {
					sb.WriteString(fmt.Sprintf("- **%s**: Tests: `%s`\n", tm.EntityName, strings.Join(tm.TestFiles, "`, `")))
				}
				sb.WriteString("\n")
			}
		}
	}
	if !hasTestIntel {
		if len(res.Testing.Frameworks) > 0 {
			sb.WriteString(fmt.Sprintf("- **Frameworks:** %s\n\n", strings.Join(res.Testing.Frameworks, ", ")))
		} else {
			sb.WriteString("No findings were produced by this analyzer.\n\n")
		}
	}

	// Section 14: Architecture Scorecard
	sb.WriteString("## 14. Architecture Scorecard\n\n")
	if res.Intelligence != nil && res.Intelligence.Scorecard != nil {
		sc := res.Intelligence.Scorecard
		sb.WriteString(fmt.Sprintf("**Overall Quality Grade:** `Grade %s` (Score: **%.1f/100**)\n\n", sc.OverallGrade, sc.OverallScore))
		if len(sc.Components) > 0 {
			sb.WriteString("| Component | Grade | Score | Rationale |\n|---|---|---|---|\n")
			for _, comp := range sc.Components {
				sb.WriteString(fmt.Sprintf("| **%s** | `%s` | %.0f%% | %s |\n", comp.Component, comp.Grade, comp.Score, comp.Rationale))
			}
			sb.WriteString("\n")
		}
		if len(sc.Recommendations) > 0 {
			sb.WriteString("### Prioritized Recommendations\n\n")
			for _, rec := range sc.Recommendations {
				sb.WriteString(fmt.Sprintf("- **[%s] %s**: %s\n", strings.ToUpper(rec.Priority), rec.Title, rec.Description))
			}
			sb.WriteString("\n")
		}
	} else {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 15: Evidence & Provenance
	sb.WriteString("## 15. Evidence & Provenance\n\n")
	sb.WriteString("### Engine Provenance\n\n")
	sb.WriteString(fmt.Sprintf("- **Engine:** `%s` (v%s)\n", res.Provenance.Engine, res.Provenance.EngineVersion))
	sb.WriteString(fmt.Sprintf("- **Rules Evaluated:** %d\n", res.Provenance.RulesEvaluatedCount))
	sb.WriteString(fmt.Sprintf("- **Complexity Tier:** `%s` (Score: %.1f)\n", res.Provenance.ComplexityTier, res.Provenance.ComplexityScore))
	if res.Provenance.SourceArtifactSha256 != "" {
		sb.WriteString(fmt.Sprintf("- **Source Artifact SHA-256:** `%s`\n", res.Provenance.SourceArtifactSha256))
	}
	sb.WriteString("\n")

	if len(res.Evidence) > 0 {
		sb.WriteString(fmt.Sprintf("### Canonical Evidence Catalog (%d items)\n\n", len(res.Evidence)))
		sb.WriteString("| Evidence ID | Source | File Path | Lines | Detector | Confidence | Description |\n|---|---|---|---|---|---|---|\n")
		limit := 40
		if len(res.Evidence) < limit {
			limit = len(res.Evidence)
		}
		for i := 0; i < limit; i++ {
			ev := res.Evidence[i]
			lines := "-"
			if ev.LineStart != nil {
				if ev.LineEnd != nil && *ev.LineEnd != *ev.LineStart {
					lines = fmt.Sprintf("%d-%d", *ev.LineStart, *ev.LineEnd)
				} else {
					lines = fmt.Sprintf("%d", *ev.LineStart)
				}
			}
			sb.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` | %s | `%s` | `%s` | %s |\n",
				ev.ID, ev.SourceType, ev.FilePath, lines, ev.Detector, ev.Confidence, ev.Description))
		}
		if len(res.Evidence) > limit {
			sb.WriteString(fmt.Sprintf("\n*(Showing %d of %d canonical evidence records)*\n", limit, len(res.Evidence)))
		}
		sb.WriteString("\n")
	} else {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 16: Environment / Deployment
	sb.WriteString("## 16. Environment / Deployment\n\n")
	if len(res.Environment.Variables) > 0 {
		sb.WriteString("### Environment Variables\n\n")
		sb.WriteString("| Variable | Inferred Type | Required | Source |\n|---|---|---|---|\n")
		for _, v := range res.Environment.Variables {
			req := "No"
			if v.Required {
				req = "Yes"
			}
			sb.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | `%s` |\n", v.Name, v.InferredType, req, v.Source))
		}
		sb.WriteString("\n")
	}
	sb.WriteString(fmt.Sprintf("- **Docker Available:** %v\n", res.Deployment.DockerAvailable))
	if len(res.Deployment.DockerfilePaths) > 0 {
		sb.WriteString(fmt.Sprintf("- **Dockerfiles:** `%s`\n", strings.Join(res.Deployment.DockerfilePaths, "`, `")))
	}
	if len(res.Deployment.ComposePaths) > 0 {
		sb.WriteString(fmt.Sprintf("- **Docker Compose Files:** `%s`\n", strings.Join(res.Deployment.ComposePaths, "`, `")))
	}
	if len(res.Deployment.CIWorkflows) > 0 {
		sb.WriteString("- **CI Workflows:**\n")
		for _, w := range res.Deployment.CIWorkflows {
			name := w.Name
			if name == "" {
				name = w.Path
			}
			sb.WriteString(fmt.Sprintf("  - `%s`\n", name))
		}
	}
	sb.WriteString("\n")

	// Section 17: Dependencies
	sb.WriteString("## 17. Dependencies\n\n")
	if len(res.Dependencies.Runtime) > 0 {
		sb.WriteString("### Runtime Dependencies\n\n")
		for _, d := range res.Dependencies.Runtime {
			sb.WriteString(fmt.Sprintf("- `%s` (%s) [%s]\n", d.Name, d.Version, d.Manager))
		}
		sb.WriteString("\n")
	}
	if len(res.Dependencies.Development) > 0 {
		sb.WriteString("### Development Dependencies\n\n")
		for _, d := range res.Dependencies.Development {
			sb.WriteString(fmt.Sprintf("- `%s` (%s) [%s]\n", d.Name, d.Version, d.Manager))
		}
		sb.WriteString("\n")
	}
	if len(res.Dependencies.Runtime) == 0 && len(res.Dependencies.Development) == 0 {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 18: Testing
	sb.WriteString("## 18. Testing\n\n")
	if len(res.Testing.Frameworks) > 0 {
		sb.WriteString(fmt.Sprintf("- **Frameworks:** %s\n", strings.Join(res.Testing.Frameworks, ", ")))
	}
	if len(res.Testing.TestCommands) > 0 {
		sb.WriteString("### Test Execution Commands\n\n```bash\n")
		for _, cmd := range res.Testing.TestCommands {
			sb.WriteString(cmd + "\n")
		}
		sb.WriteString("```\n\n")
	}
	if len(res.Testing.Frameworks) == 0 && len(res.Testing.TestCommands) == 0 {
		sb.WriteString("No findings were produced by this analyzer.\n\n")
	}

	// Section 19: Limitations / Confidence
	sb.WriteString("## 19. Limitations / Confidence\n\n")
	sb.WriteString("- **Epistemic Confidence Framework:** Findings are strictly tagged as `CONFIRMED` (directly proven by manifests/AST), `STRONGLY_INFERRED` (high-confidence heuristic matches), or `WEAKLY_INFERRED` (indirect signal).\n")
	sb.WriteString("- **Deterministic Analysis:** Analysis is 100% reproducible and operates fail-closed on local repository source trees.\n")
	sb.WriteString("- **Language Resolution Boundary:** Go, TypeScript, JavaScript, Python, Rust, and Dockerfiles are supported with native AST and manifest extractors.\n")

	return sb.String()
}
