root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ."
bin = "tmp/server"
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "json"]
exclude_dir = [
    "tmp",
    ".git",
    ".idea",
    ".vscode",
    "archive",
    "dist",
    "build",
    "vendor",
    "venv",
]
delay = 1000

[log]
time = true

[misc]
clean_on_exit = true