FROM golang:1.26-bookworm

ENV DEBIAN_FRONTEND=noninteractive \
    PORT=10000 \
    CHROMIUM_PATH=/usr/bin/chromium

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    chromium \
    && rm -rf /var/lib/apt/lists/*

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY .air.toml .

EXPOSE 10000

CMD ["air", "-c", ".air.toml"]