package studio

import "errors"

var (
	ErrDocumentNotFound    = errors.New("studio document not found")
	ErrSessionNotFound     = errors.New("studio session not found")
	ErrSessionExpired      = errors.New("studio session expired")
	ErrUnauthorized        = errors.New("unauthorized studio session access")
	ErrVersionNotFound     = errors.New("studio version not found")
	ErrInvalidBaseVersion  = errors.New("base version does not match active session version")
	ErrConflict            = errors.New("optimistic concurrency conflict on session")
	ErrIdempotencyConflict = errors.New("idempotency key conflict with mismatched operation parameters")
	ErrAssetNotFound       = errors.New("studio asset not found")
	ErrSnapshotNotFound    = errors.New("studio snapshot not found")
	ErrInvalidOperation    = errors.New("invalid studio operation parameters")
	ErrNoParentVersion     = errors.New("cannot undo: version has no parent")
	ErrNoRedoChild         = errors.New("cannot redo: version has no child branch")
	ErrInvalidBranchTarget = errors.New("target version does not belong to this document")
	ErrInvalidSourcePDF    = errors.New("uploaded source document is not a readable PDF")
	ErrSourceTooLarge      = errors.New("uploaded source document exceeds the Studio size limit")
	ErrSourcePageLimit     = errors.New("uploaded source document exceeds the Studio page limit")
	ErrEncryptedSourcePDF  = errors.New("password-protected PDFs must be unlocked before opening Studio")
	ErrUnknownCommand      = errors.New("unknown studio command")
	ErrInvalidCommand      = errors.New("invalid studio command parameters")
	ErrCommandPageNotFound = errors.New("studio command references an unknown page")
	ErrDuplicatePageID     = errors.New("studio command contains duplicate page IDs")
	ErrInvalidPageOrder    = errors.New("reorder command must contain every page exactly once")
	ErrCannotDeleteAll     = errors.New("studio document must retain at least one page")
	ErrBlankDimensions     = errors.New("blank page dimensions cannot be derived from the document")
	ErrInvalidCropBox      = errors.New("studio crop box is invalid for the selected page")
	ErrInvalidMetadata     = errors.New("studio metadata contains invalid characters")
)
